CREATE TABLE IF NOT EXISTS board_policies (
    id TEXT PRIMARY KEY,
    directive TEXT NOT NULL,
    active INTEGER NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
